### ISSUE TITLE
Add Code for Portland event

### ISSUE THREAD

**Issue by ungoldman** [cascadiajs/pdx.devweek.org#2]
- **Date(s)**: July 29
- **Start Time**: 6:00pm
- **End Time**: 9:00pm
- **Location**: Esri Portland R&D Center http://calagator.org/venues/202394387
- **Link to logo image (100 x 100 pixels)**: https://avatars3.githubusercontent.com/u/6692606?s=100
- **Link to webpage**: http://www.meetup.com/Code-for-Portland/events/193530482/
- **Brief description**: Code for Portland is a local volunteer-run Code for America brigade focused on civic hacking projects and open data initiatives. Join us at our monthly hack night to chat, eat pizza, and collaborate on civic-minded tech projects!

**Comment by crtr0** [comment]
Added, thank you!

**Comment by ungoldman** [comment]
:+1:
