### ISSUE TITLE
JavaScript Beginners Workshop

### ISSUE THREAD

**Issue by maureendugan** [cascadiajs/pdx.devweek.org#3]
Date(s) Wednesday: 7/30/14
Start Time: 6:00pm
End Time (optional): 8:00pm
Location: Epicodus, 208 SW 5th Ave, Portland, OR 97204
Link to logo image (100 x 100 pixels): https://drive.google.com/file/d/0B78U4iHMLq1Wa2d3NWhuMjh4VEE/edit?usp=sharing
Link to webpage: https://www.eventbrite.com/edit?eid=8605177317
Brief description (1-3 sentences):
No coding experience is necessary! We'll cover the basics of how the web works, what part languages and frameworks and other buzzwords play, and then we'll dive into some programming fundamentals using JavaScript! By the end, you'll have a good sense of how to continue learning web programming.

**Comment by crtr0** [comment]
Added, thank you!
