### ISSUE TITLE
TUIO Jam - Create Interactive Art

### ISSUE THREAD

**Issue by zeromhz** [cascadiajs/pdx.devweek.org#4]
Date: Saturday August 2nd, 2014
Start Time: 11:00AM
End Time: 8:00PM (Demos at 6:30PM) 
Location: Instrument - 419 NE 10th Ave
URL: http://ctrl-art.github.io/tuio-jam/
Note: Registration required. Space is limited.
Description: We are hosting a hack day in which participants will create unique electronic artworks that are all driven from a common touch surface. So one person touching one computer will cause all artworks to react. The goal is to create a gallery showing in which all art in the gallery reacts in tandem to one viewers touches. Select art pieces created at the hack day will be exhibited at the TUIO Art Show at the Diode Gallery on August 16th. 

![tuiojam](https://cloud.githubusercontent.com/assets/279976/3635462/32550e98-0f73-11e4-8ac5-ecc7683c3e64.jpg)

**Comment by crtr0** [comment]
Added, thank you!
