### ISSUE TITLE
IndieWeb Hack Night

### ISSUE THREAD

**Issue by aaronpk** [cascadiajs/pdx.devweek.org#5]
Date: July 30th
Start Time: 6:30pm 
End Time: 9:00pm
Location: Esri R&D Center
Link to logo image: 
![iwc-logo-100](https://cloud.githubusercontent.com/assets/113001/3711448/6ab5bd7e-14d6-11e4-8a55-4099d6e4593c.png)
Link to webpage: http://indiewebcamp.com/events/2014-07-30-homebrew-website-club
Brief description: The IndieWeb is a people-focused alternative to the siloed web. Come join a group of people passionate about creating, improving, building, designing their own websites for an evening of working on your projects and learning how to add IndieWeb features to your website!

**Comment by ungoldman** [comment]
:+1:

**Comment by crtr0** [comment]
Added!
